export const tableData = [
  {
      id:1,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Complete',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'Pakistan',
      serving:'2 person',
      duration:'30 m'
  },
  {
      id:2,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Pending',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'India',
      serving:'1 person',
      duration:'50 m'
  },
  {
      id:1,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Declined',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Female',
      location:'Pakistan',
      serving:'2 person',
      duration:'40 m'
  },
  {
      id:2,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Complete',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'Pakistan',
      serving:'3 person',
      duration:'30 m'
  },
  {
      id:1,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Pending',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Female',
      location:'India',
      serving:'4 person',
      duration:'10 m'
  },
  {
      id:2,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Declined',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'Pakistan',
      serving:'3 person',
      duration:'20 m'
  },
  {
      id:1,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Complete',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Female',
      location:'Pakistan',
      serving:'2 person',
      duration:'30 m'
  },
  {
      id:2,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Pending',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'Pakistan',
      serving:'4 person',
      duration:'40 m'
  },
  {
      id:1,
      recipeName:'Red Chiken',
      dateAndTime:'03 May 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Declined',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Female',
      location:'India',
      serving:'3 person',
      duration:'30 m'
  },
  {
      id:2,
      recipeName:'Red Chiken',
      dateAndTime:'03 September 2024',
      placedBy:'User name',
      placedOn:'Mar 4, 2024',
      chefname:'Mark Don',
      amount:'$56',
      sectionType:'Stranded',
      rating:'4.5',
      categories:'Produce',
      price:'$456',
      quentity:'1 kg',
      type:'Categories',
      status:'Complete',
      phone:'+92703292493',
      mail:'admin@builtinsoft.com',
      gender:'Male',
      location:'Pakistan',
      serving:'2 person',
      duration:'20 m'
  },
]
